---
- name: Create and push hr-hiring image
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/tools.yml

  tasks:
    - include_role:
        name: ../roles/podmanize
